language: cpp
compiler: gcc

# Change this to your needs
script: autoreconf -i && ./configure && make && make check

before_install:
 - sudo apt-get update
 - sudo apt-get install libcppunit-dev libcppunit-1.12-1

