language: cpp
compiler: gcc

# Change this to your needs
script: autoreconf -i && ./configure && make && make check

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcppunit-dev

