language: cpp
compiler: gcc

script: autoreconf -i && ./configure && make && make check

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcppunit-dev

notifications:
  email:
    recipients:
      - fjousseaume@fortress-combat.fr
    on_success: change
    on_failure: always

